version: "3.9"
services:
  nginx:
    ports:
      - "80:80"
  node-app:
    build:
      context: .
      args:
        - NODE_ENV: production
    environment:
      - NODE_ENV=production
      - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DB}
    command: npm run build:start
  mysql:
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DB}